"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { Accessibility, ArrowLeft, ArrowRight, BarChart3, BookOpen, Building2, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronRight, CircleHelp, Clock3, Download, FileCheck2, FileText, Globe2, HeartHandshake, Home, Landmark, Mail, MapPin, Menu, MessageCircle, Navigation, Phone, Printer, Search, ShieldCheck, Smartphone, Users, X } from "lucide-react";

const RAW_SERVICES = [
  ["KEL-001","Kartu Tanda Penduduk Elektronik (KTP-el)","Pendaftaran Penduduk","Kelurahan"],
  ["KEL-002","Kartu Keluarga (KK)","Pendaftaran Penduduk","Kelurahan"],
  ["KEL-003","Kartu Identitas Anak (KIA)","Pendaftaran Penduduk","Kelurahan"],
  ["KEL-004","Akta Kelahiran","Pencatatan Sipil","Kelurahan"],
  ["KEL-005","Akta Kematian","Pencatatan Sipil","Kelurahan"],
  ["KEL-006","Pindah Datang","Pendaftaran Penduduk","Kelurahan"],
  ["KEC-001","Pencatatan Kelahiran WNI Terintegrasi dengan Fasilitas Kesehatan","Pencatatan Sipil","Kecamatan"],
  ["KEC-002","Pencatatan Kematian WNI Terintegrasi dengan Fasilitas Kesehatan","Pencatatan Sipil","Kecamatan"],
  ["KEC-003","Pencatatan Perkawinan WNI Terintegrasi dengan Rumah Ibadah","Pencatatan Sipil","Kecamatan"],
  ["KEC-004","Pencatatan Perkawinan WNI","Pencatatan Sipil","Kecamatan"],
  ["KEC-005","Pencatatan Perceraian WNI","Pencatatan Sipil","Kecamatan"],
  ["KEC-006","Perpindahan Penduduk WNI ke Luar Daerah","Pendaftaran Penduduk","Kecamatan"],
  ["KEC-007","Pendataan Penduduk Nonpermanen","Pendaftaran Penduduk","Kecamatan"],
  ["KEC-008","Penerbitan Kembali Kutipan Akta karena Rusak atau Hilang","Pencatatan Sipil","Kecamatan"],
  ["KEC-009","Legalisasi Dokumen Kependudukan Non-Digital atau Belum TTE","Dokumen Kependudukan","Kecamatan"],
  ["SUD-001","Pencatatan Biodata WNI di Dalam atau Luar Wilayah NKRI","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-002","Penerbitan Kartu Keluarga Baru WNI","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-003","Penerbitan KTP-el Baru WNI","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-004","Penerbitan Kartu Identitas Anak WNI","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-005","Perpindahan Penduduk WNI Dalam NKRI","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-006","Pembatalan Dokumen Pendaftaran Penduduk (Contrarius Actus)","Perubahan Data","Suku Dinas"],
  ["SUD-007","Perekaman KTP-el bagi Penduduk yang Tidak Dapat Melapor Sendiri","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-008","Dokumen Kependudukan Terintegrasi dengan KUA","Pendaftaran Penduduk","Suku Dinas"],
  ["SUD-009","Pencatatan Kelahiran Anak yang Tidak Diketahui Asal-Usulnya","Pencatatan Sipil","Suku Dinas"],
  ["SUD-010","Pencatatan Perkawinan Penduduk WNI","Pencatatan Sipil","Suku Dinas"],
  ["SUD-011","Pencatatan Perkawinan ketika Salah Satu atau Kedua Pihak Meninggal","Pencatatan Sipil","Suku Dinas"],
  ["SUD-012","Pencatatan Pembatalan Perkawinan WNI","Pencatatan Sipil","Suku Dinas"],
  ["SUD-013","Pencatatan Perceraian WNI","Pencatatan Sipil","Suku Dinas"],
  ["SUD-014","Pencatatan Pembatalan Perceraian WNI","Pencatatan Sipil","Suku Dinas"],
  ["SUD-015","Pencatatan Kematian dalam Wilayah NKRI","Pencatatan Sipil","Suku Dinas"],
  ["SUD-016","Pencatatan Pengangkatan Anak WNI","Pencatatan Sipil","Suku Dinas"],
  ["SUD-017","Pencatatan Pengakuan Anak","Pencatatan Sipil","Suku Dinas"],
  ["SUD-018","Pencatatan Pengesahan Anak","Pencatatan Sipil","Suku Dinas"],
  ["SUD-019","Pencatatan Perubahan Nama Penduduk WNI","Perubahan Data","Suku Dinas"],
  ["SUD-020","Pencatatan Perubahan Akta Pencatatan Sipil","Perubahan Data","Suku Dinas"],
  ["SUD-021","Pembetulan Akta Pencatatan Sipil","Perubahan Data","Suku Dinas"],
  ["SUD-022","Pembatalan Akta berdasarkan Putusan Pengadilan","Perubahan Data","Suku Dinas"],
  ["SUD-023","Pembatalan Akta tanpa Putusan Pengadilan","Perubahan Data","Suku Dinas"],
  ["SUD-024","Penerbitan Kembali Kutipan Akta karena Rusak, Hilang, atau Sengketa","Pencatatan Sipil","Suku Dinas"],
  ["SUD-025","Pelaporan Perjanjian Perkawinan Sebelum Perkawinan","Pencatatan Sipil","Suku Dinas"],
  ["SUD-026","Pelaporan Perjanjian Perkawinan Selama Perkawinan","Pencatatan Sipil","Suku Dinas"],
  ["SUD-027","Pelaporan Perubahan atau Pencabutan Perjanjian Perkawinan","Pencatatan Sipil","Suku Dinas"],
  ["SUD-028","Pencatatan Peristiwa Penting Lainnya","Pencatatan Sipil","Suku Dinas"],
  ["SUD-029","Legalisasi Dokumen Kependudukan Belum Digital atau Belum TTE","Dokumen Kependudukan","Suku Dinas"],
  ["SUD-030","Konfirmasi Dokumen Kependudukan","Dokumen Kependudukan","Suku Dinas"],
];
const services = RAW_SERVICES.map(([id,title,category,location])=>({id,title,category,location,channel:`${location} atau kanal daring`}));
const intentions = [["Punya anak","Urus kelahiran, KIA, dan pembaruan KK","kelahiran",Users],["Pindah tempat tinggal","Temukan layanan pindah datang atau keluar","pindah",Navigation],["Dokumen hilang/rusak","Terbitkan kembali dokumen kependudukan","rusak",FileCheck2],["Menikah atau bercerai","Catat peristiwa dan perubahan dokumen","perkawinan",HeartHandshake]];
const news = [["Pengumuman","Implementasi Sistem Informasi Administrasi Kependudukan Terpusat","Informasi layanan"],["Pelayanan","Pastikan data pada dokumen kependudukan Anda sudah sesuai","Panduan warga"],["PPID","Akses informasi publik, formulir, dan dokumen layanan","Informasi publik"]];
const faq = [["Apakah layanan administrasi kependudukan dipungut biaya?","Tidak. Seluruh layanan administrasi kependudukan dan pencatatan sipil tidak dipungut biaya."],["Di mana saya harus mengurus dokumen?","Cari layanan yang dibutuhkan terlebih dahulu. Rincian layanan menunjukkan tingkat unit dan kanal pengurusannya."],["Bagaimana jika persyaratan belum lengkap?","Gunakan daftar periksa pada rincian layanan dan lengkapi dokumen sebelum mengajukan."],["Bagaimana menyampaikan keluhan?","Gunakan kanal bantuan dan pengaduan resmi pada bagian Bantuan Warga."]];
const informationItems = [
 {id:"gratis",tag:"Pengumuman",title:"Seluruh layanan administrasi kependudukan tidak dipungut biaya",date:"Informasi layanan",summary:"Warga tidak dikenakan biaya untuk penerbitan dokumen administrasi kependudukan.",body:["Seluruh pelayanan administrasi kependudukan dan pencatatan sipil diberikan tanpa pungutan biaya.","Gunakan hanya kanal resmi Dukcapil. Laporkan apabila terdapat permintaan pembayaran, imbalan, atau pengiriman data pribadi melalui kanal yang tidak dapat diverifikasi."],links:[["Laporkan melalui CRM Jakarta","https://pengaduanwarga.jakarta.go.id/"]]},
 {id:"siak",tag:"Pengumuman",title:"Implementasi Sistem Informasi Administrasi Kependudukan Terpusat",date:"Pembaruan sistem",summary:"Penyesuaian sistem dapat memengaruhi waktu pemrosesan pada unit pelayanan.",body:["Dukcapil menerapkan Sistem Informasi Administrasi Kependudukan terpusat untuk menjaga konsistensi dan keamanan data penduduk.","Apabila terjadi penyesuaian layanan, simpan bukti permohonan dan pantau informasi pada ticker pengumuman portal ini."],links:[]},
 {id:"data",tag:"Panduan",title:"Pastikan data pada dokumen kependudukan sudah sesuai",date:"Panduan warga",summary:"Periksa nama, tempat dan tanggal lahir, alamat, serta elemen data lain sebelum meninggalkan loket.",body:["Cocokkan seluruh elemen data pada dokumen yang diterima dengan dokumen pendukung yang diajukan.","Jika menemukan ketidaksesuaian, segera konsultasikan kepada petugas pada unit yang menerbitkan dokumen dengan membawa dokumen pendukung asli."],links:[]},
 {id:"forms",tag:"Formulir",title:"Pusat formulir administrasi kependudukan",date:"Dokumen warga",summary:"Panduan memilih formulir untuk pendaftaran penduduk dan pencatatan sipil.",body:["Formulir dikelompokkan menurut peristiwa: biodata dan keluarga, perpindahan penduduk, kelahiran, kematian, perkawinan, perceraian, serta perubahan elemen data.","Petugas akan memastikan formulir yang tepat berdasarkan peristiwa dan kewenangan unit pelayanan. Siapkan identitas serta dokumen pendukung sebelum mengisi."],links:[]},
 {id:"statistics",tag:"Statistik",title:"Statistik dan publikasi kependudukan Jakarta",date:"Data kependudukan",summary:"Akses ringkasan jenis data, profil perkembangan penduduk, dan statistik vital.",body:["Publikasi Dukcapil mencakup profil perkembangan kependudukan, statistik vital, hasil pelayanan pendaftaran penduduk dan pencatatan sipil, serta publikasi tematik kelahiran dan kematian.","Data agregat digunakan untuk perencanaan layanan. Portal ini tidak menampilkan NIK atau data individu."],links:[]},
 {id:"standards",tag:"Standar",title:"Standar pelayanan administrasi kependudukan",date:"Jaminan pelayanan",summary:"Rangkuman prinsip biaya, waktu, produk layanan, dan penanganan pengaduan.",body:["Setiap standar pelayanan memuat dasar hukum, persyaratan, prosedur, jangka waktu, biaya, produk layanan, sarana, kompetensi pelaksana, pengawasan, dan penanganan pengaduan.","Rincian operasional mengikuti jenis layanan serta unit yang berwenang. Konfirmasikan pada direktori wilayah sebelum kunjungan."],links:[]},
 {id:"pledge",tag:"Maklumat",title:"Maklumat pelayanan Dukcapil DKI Jakarta",date:"Komitmen mutu",summary:"Komitmen pelayanan yang mudah, transparan, akuntabel, dan bebas pungutan.",body:["Dukcapil berkomitmen menyelenggarakan pelayanan sesuai standar yang ditetapkan serta melakukan perbaikan berkelanjutan.","Warga berhak menyampaikan pengaduan bila pelayanan tidak sesuai standar atau terdapat dugaan penyalahgunaan wewenang."],links:[["Kirim pengaduan","https://pengaduanwarga.jakarta.go.id/"]]},
];

const Emblem=()=> <Image className="emblem" src="/logo-dukcapil.svg" width={103} height={55} alt="Logo Dinas Kependudukan dan Pencatatan Sipil" priority/>;
const External=({href,children,className=""})=><a className={className} href={href} target="_blank" rel="noreferrer">{children}</a>;
function Title({eyebrow,title,text,action}){return <div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{text&&<p className="lead">{text}</p>}</div>{action}</div>}

export default function Page(){
 const [view,setView]=useState("home"),[menu,setMenu]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("Semua"),[location,setLocation]=useState("Semua"),[selected,setSelected]=useState(null),[selectedInfo,setSelectedInfo]=useState(null),[openFaq,setOpenFaq]=useState(0),[accessible,setAccessible]=useState(false);
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return services.filter(s=>(!q||`${s.title} ${s.category} ${s.location}`.toLowerCase().includes(q))&&(category==="Semua"||s.category===category)&&(location==="Semua"||s.location===location))},[query,category,location]);
 const go=(v)=>{setView(v);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const find=(q="")=>{setQuery(q);setCategory("Semua");setLocation("Semua");go("services")};
 const openService=(s)=>{setSelected(s);go("detail")};
 const openInfo=(id)=>{setSelectedInfo(informationItems.find(item=>item.id===id));go("info-detail")};
 return <div className={`site ${accessible?"accessible":""}`}><a className="skip" href="#main">Lewati ke konten utama</a>
  <div className="govbar"><div className="shell govrow"><span><Landmark size={14}/> Pemerintah Provinsi DKI Jakarta</span><button aria-pressed={accessible} onClick={()=>setAccessible(!accessible)}><Accessibility size={14}/> {accessible?"Mode standar":"Kontras & teks besar"}</button></div></div>
  <div className="announcement"><div className="shell"><b>PENGUMUMAN</b><div className="ticker" aria-label="Pengumuman layanan"><div>{informationItems.filter(x=>x.tag==="Pengumuman").map(x=><button key={x.id} onClick={()=>openInfo(x.id)}>{x.title}<span>•</span></button>)}</div></div><button className="ticker-all" onClick={()=>go("information")}>Semua <ArrowRight/></button></div></div>
  <header className="header"><div className="shell headrow"><button className="brand" onClick={()=>go("home")}><Emblem/><span><small>Dinas Kependudukan dan Pencatatan Sipil</small><b>Provinsi DKI Jakarta</b></span></button><nav className="desktop-nav">{[["Beranda","home"],["Layanan","services"],["Lokasi & Kanal","locations"],["Informasi","information"],["PPID","ppid"]].map(([l,v])=><button className={view===v?"active":""} key={v} onClick={()=>v==="services"?find():go(v)}>{l}</button>)}<button className="help-btn" onClick={()=>go("help")}>Bantuan Warga</button></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Buka menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="shell mobile-nav">{[["Beranda","home"],["Layanan","services"],["Lokasi & Kanal","locations"],["Informasi","information"],["PPID","ppid"],["Bantuan Warga","help"]].map(([l,v])=><button key={v} onClick={()=>v==="services"?find():go(v)}>{l}</button>)}</nav>}</header>
  <main id="main">
   {view==="home"&&<HomeView query={query} setQuery={setQuery} find={find} go={go} openInfo={openInfo}/>}
   {view==="services"&&<ServicesView query={query} setQuery={setQuery} category={category} setCategory={setCategory} location={location} setLocation={setLocation} filtered={filtered} openService={openService}/>}
   {view==="detail"&&selected&&<Detail service={selected} back={()=>go("services")} locations={()=>go("locations")} openInfo={openInfo}/>} 
   {view==="locations"&&<Locations/>}{view==="information"&&<Information openInfo={openInfo}/>} {view==="info-detail"&&selectedInfo&&<InformationDetail item={selectedInfo} back={()=>go("information")}/>} {view==="help"&&<Help openFaq={openFaq} setOpenFaq={setOpenFaq}/>} {view==="ppid"&&<Ppid/>}
  </main><Footer find={find} go={go} openInfo={openInfo}/>
 </div>
}

function HomeView({query,setQuery,find,go,openInfo}){return <>
 <section className="hero"><Image className="hero-bg" src="/monas-jakarta.jpg" fill sizes="100vw" alt="Monumen Nasional dan lanskap pusat Jakarta" priority/><div className="shell hero-inner"><div className="hero-copy glass-panel"><span className="official"><ShieldCheck size={15}/> Portal layanan warga Jakarta</span><h1>Administrasi kependudukan,<br/><em>lebih mudah.</em></h1><p>Temukan layanan berdasarkan kebutuhan, periksa dokumen yang diperlukan, lalu pilih kanal pelayanan yang tepat.</p><div className="trust"><span><Check/> Tanpa pungutan</span><span><Check/> Informasi terstruktur</span><span><Check/> Kanal resmi</span></div></div><div className="search-card glass-panel"><span className="search-kicker">MULAI DARI SINI</span><h2>Apa yang ingin Anda urus?</h2><form onSubmit={e=>{e.preventDefault();find(query)}}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="KTP, kartu keluarga, akta lahir..." aria-label="Kata kunci layanan"/><button>Cari</button></form><small>Paling banyak dicari</small><div className="popular">{["KTP-el","Kartu Keluarga","Akta Kelahiran","Pindah Datang"].map(x=><button key={x} onClick={()=>find(x)}>{x}<ChevronRight/></button>)}</div><div className="all"><span>Belum tahu nama layanannya?</span><button onClick={()=>find()}>Lihat semua</button></div></div></div><div className="photo-credit">Foto: Lanskap Monas, Jakarta</div></section>
 <section className="shell shortcuts">{[[FileText,"Cari layanan","Temukan layanan dan persyaratan",()=>find()],[MapPin,"Lokasi pelayanan","Cari kantor dan kanal layanan",()=>go("locations")],[CircleHelp,"Bantuan warga","FAQ, kontak, dan pengaduan",()=>go("help")],[BookOpen,"Informasi publik","Akses dokumen PPID",()=>go("ppid")]].map(([Icon,t,d,fn])=><button key={t} onClick={fn}><i><Icon/></i><span><b>{t}</b><small>{d}</small></span></button>)}</section>
 <section className="shell live-services"><External href="https://alpukat-dukcapil.jakarta.go.id/"><Smartphone/><span><small>Permohonan daring</small><b>ALPUKAT Betawi</b><em>Ajukan layanan dari ponsel</em></span><ArrowRight/></External><button onClick={()=>openInfo("forms")}><Download/><span><small>Pusat dokumen</small><b>Formulir Adminduk</b><em>Pilih formulir yang tepat</em></span><ArrowRight/></button><button onClick={()=>openInfo("statistics")}><BarChart3/><span><small>Data kependudukan</small><b>Statistik Jakarta</b><em>Buka ringkasan publikasi</em></span><ArrowRight/></button></section>
 <section className="shell section"><Title eyebrow="Berdasarkan kebutuhan" title="Saya ingin..." text="Mulai dari peristiwa yang sedang Anda alami. Kami akan mengarahkan Anda ke layanan yang sesuai." action={<button className="text-link" onClick={()=>find()}>Lihat 45 layanan <ArrowRight/></button>}/><div className="intentions">{intentions.map(([t,d,q,Icon],i)=><button key={t} onClick={()=>find(q)}><i className={`color-${i}`}><Icon/></i><h3>{t}</h3><p>{d}</p><span>Temukan layanan <ArrowRight/></span></button>)}</div></section>
 <section className="guide"><div className="shell guide-grid"><div><p className="eyebrow">Panduan layanan</p><h2 className="section-title">Dari kebutuhan sampai dokumen selesai</h2><p className="lead">Setiap halaman layanan menyatukan informasi yang Anda perlukan agar tidak berpindah-pindah menu.</p><button className="primary" onClick={()=>find()}>Mulai cari layanan <ArrowRight/></button></div><ol>{[["01","Temukan layanan","Cari berdasarkan dokumen atau peristiwa."],["02","Periksa persyaratan","Gunakan daftar periksa sebelum mengajukan."],["03","Pilih kanal yang tepat","Lihat unit layanan dan opsi pengurusan."],["04","Ajukan dan simpan bukti","Ikuti kanal resmi serta simpan nomor pengajuan."]].map(([n,t,d])=><li key={n}><b>{n}</b><span><strong>{t}</strong><small>{d}</small></span></li>)}</ol></div></section>
 <section className="shell section"><Title eyebrow="Kanal pelayanan" title="Pilih cara mengurus yang paling sesuai" text="Mulai secara daring atau datang ke unit wilayah setelah persyaratan dipastikan lengkap."/><div className="channel-grid"><article><i><Smartphone/></i><h3>Permohonan online</h3><p>Ajukan layanan yang tersedia melalui ALPUKAT Betawi dan simpan nomor permohonan.</p><External href="https://alpukat-dukcapil.jakarta.go.id/">Buka layanan online <ArrowRight/></External></article><article><i><Building2/></i><h3>Pelayanan wilayah</h3><p>Temukan Suku Dinas, kecamatan, atau kelurahan yang sesuai dengan jenis layanan.</p><button onClick={()=>go("locations")}>Cari unit pelayanan <ArrowRight/></button></article><article><i><MessageCircle/></i><h3>Bantuan & pengaduan</h3><p>Hubungi WhatsApp Dukcapil atau sampaikan pengaduan melalui CRM Jakarta.</p><button onClick={()=>go("help")}>Pilih kanal bantuan <ArrowRight/></button></article></div></section>
 <section className="shell section"><Title eyebrow="Informasi terkini" title="Pengumuman untuk warga" text="Informasi penting terkait pelayanan administrasi kependudukan di DKI Jakarta."/><div className="news">{news.map(([tag,t,date],i)=><article key={t} className={`news-${i}`}><span>{tag}</span><h3>{t}</h3><small><CalendarDays/> {date}</small><button onClick={()=>go("information")}>Baca informasi <ArrowRight/></button></article>)}</div></section>
 <section className="pledge"><div className="shell pledge-grid"><div><p className="eyebrow">Komitmen pelayanan</p><h2>Maklumat pelayanan Dukcapil</h2><p>Kami berkomitmen memberikan pelayanan administrasi kependudukan yang mudah, cepat, transparan, dan bebas pungutan sesuai standar pelayanan yang berlaku.</p><button className="pledge-link" onClick={()=>openInfo("pledge")}>Baca maklumat <ArrowRight/></button></div><div className="visit-card"><Clock3/><span><small>Sebelum datang</small><b>Periksa jam dan unit pelayanan</b><p>Jadwal dapat berbeda antarwilayah. Konfirmasikan melalui direktori wilayah sebelum berkunjung.</p></span><button onClick={()=>go("locations")}>Buka direktori</button></div></div></section>
 <section className="complaint"><div className="shell"><div><small>LAYANAN PENGADUAN MASYARAKAT</small><h2>Ada kendala atau layanan tidak sesuai?</h2><p>Sampaikan melalui kanal resmi agar laporan tercatat dan dapat ditindaklanjuti.</p></div><div><External href="https://pengaduanwarga.jakarta.go.id/">Kirim pengaduan</External><External href="https://pengaduanwarga.jakarta.go.id/">Lacak laporan</External></div></div></section>
 <section className="cta"><div className="shell"><div><small>Butuh bantuan?</small><h2>Kami siap membantu menemukan layanan Anda.</h2><p>Akses FAQ, nomor layanan, kanal pengaduan, dan panduan penggunaan portal.</p></div><button onClick={()=>go("help")}>Buka bantuan warga</button></div></section>
 </>}

function ServicesView(p){const reset=()=>{p.setQuery("");p.setCategory("Semua");p.setLocation("Semua")};return <section className="shell page"><p className="eyebrow">Direktori pelayanan</p><h1 className="page-title">Temukan layanan kependudukan</h1><p className="lead">Cari berdasarkan dokumen, peristiwa, kategori, atau unit pelayanan.</p><div className="results-layout"><aside><label className="search-field"><Search/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Ketik kata kunci..."/></label><Filter label="Kategori" value={p.category} set={p.setCategory} options={["Semua",...new Set(services.map(s=>s.category))]}/><Filter label="Unit pelayanan" value={p.location} set={p.setLocation} options={["Semua","Kelurahan","Kecamatan","Suku Dinas"]}/><button className="reset" onClick={reset}>Atur ulang filter</button></aside><div><div className="result-head"><span><b>{p.filtered.length} layanan ditemukan</b><h2>Hasil pencarian</h2></span>{p.query&&<mark>Kata kunci: “{p.query}”</mark>}</div>{p.filtered.length?<div className="service-list">{p.filtered.map(s=><button key={s.id} onClick={()=>p.openService(s)}><div><span className="tags"><i>{s.category}</i><i><MapPin/> {s.location}</i></span><h3>{s.title}</h3><p>{s.channel} · ID {s.id}</p></div><ChevronRight/></button>)}</div>:<div className="empty"><Search/><h3>Layanan belum ditemukan</h3><p>Coba kata yang lebih umum seperti “KTP”, “lahir”, atau “pindah”.</p><button className="primary" onClick={reset}>Tampilkan semua layanan</button></div>}</div></div></section>}
function Filter({label,value,set,options}){return <label className="filter"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}

function Detail({service,back,locations,openInfo}){return <section className="shell page"><button className="back" onClick={back}><ArrowLeft/> Kembali ke daftar layanan</button><article className="detail"><header><span>{service.category}</span><span>{service.location}</span><h1>{service.title}</h1><p>Kode direktori {service.id}</p></header><div className="detail-grid"><div className="detail-main"><Block icon={FileText} title="Tentang layanan"><p>Layanan ini termasuk dalam kategori <b>{service.category}</b> dan dilayani pada tingkat <b>{service.location}</b>.</p></Block><Block icon={FileCheck2} title="Persyaratan dan formulir"><div className="notice"><ShieldCheck/><span><b>Periksa sebelum mengajukan</b><p>Jenis dokumen pendukung mengikuti peristiwa kependudukan dan kondisi pemohon. Gunakan pusat formulir internal untuk memilih kelompok dokumen yang tepat.</p><button className="inline-link" onClick={()=>openInfo("forms")}>Buka pusat formulir <ArrowRight/></button></span></div></Block><Block icon={Navigation} title="Alur pengurusan"><ol className="steps">{[["1","Verifikasi","Periksa dokumen pendukung."],["2","Pilih kanal","Datang atau gunakan kanal daring."],["3","Simpan bukti","Catat nomor pengajuan."]].map(([n,t,d])=><li key={n}><small>LANGKAH {n}</small><b>{t}</b><p>{d}</p></li>)}</ol></Block><Block icon={CircleHelp} title="Informasi penting"><p>Layanan administrasi kependudukan tidak dipungut biaya. Gunakan hanya kanal resmi dan jangan membagikan NIK atau dokumen pribadi melalui kanal tidak dikenal.</p></Block></div><aside className="detail-side"><div><small>Unit pelayanan</small><h3><MapPin/> {service.location}</h3><p>{service.channel}</p><button onClick={locations}>Cari lokasi pelayanan</button></div><div className="before"><b>Sebelum mengajukan</b><p><CheckCircle2/> Cocokkan persyaratan</p><p><CheckCircle2/> Siapkan dokumen asli</p><p><CheckCircle2/> Simpan bukti pengajuan</p></div><button className="print" onClick={()=>window.print()}><Printer/> Cetak panduan</button></aside></div></article></section>}
function Block({icon:Icon,title,children}){return <section className="block"><h2><i><Icon/></i>{title}</h2><div>{children}</div></section>}

function Locations(){const units=[[Building2,"Jakarta Pusat","Kantor Wali Kota Jakarta Pusat","https://www.google.com/maps/search/?api=1&query=Suku+Dinas+Dukcapil+Jakarta+Pusat"],[Landmark,"Jakarta Utara","Kantor Wali Kota Jakarta Utara","https://www.google.com/maps/search/?api=1&query=Suku+Dinas+Dukcapil+Jakarta+Utara"],[Globe2,"Jakarta Barat","Kantor Wali Kota Jakarta Barat","https://www.google.com/maps/search/?api=1&query=Suku+Dinas+Dukcapil+Jakarta+Barat"],[Home,"Jakarta Selatan","Kantor Wali Kota Jakarta Selatan","https://www.google.com/maps/search/?api=1&query=Suku+Dinas+Dukcapil+Jakarta+Selatan"],[Building2,"Jakarta Timur","Kantor Wali Kota Jakarta Timur","https://www.google.com/maps/search/?api=1&query=Suku+Dinas+Dukcapil+Jakarta+Timur"],[Navigation,"Kepulauan Seribu","Kantor Kabupaten Kepulauan Seribu","https://www.google.com/maps/search/?api=1&query=Suku+Dinas+Dukcapil+Kepulauan+Seribu"]];return <SimplePage eyebrow="Lokasi & kanal" title="Pilih unit pelayanan yang tepat" text="Direktori wilayah tersedia langsung di portal baru. Gunakan peta hanya untuk navigasi perjalanan."><div className="cards">{units.map(([Icon,t,d,url])=><article key={t}><i><Icon/></i><h2>{t}</h2><p>{d}</p><External href={url}>Buka petunjuk arah <ArrowRight/></External></article>)}</div><div className="warning"><b>Kantor Dinas:</b> Jl. Letjen S. Parman No. 7, Tomang, Grogol Petamburan, Jakarta Barat. Jam pelayanan perlu dikonfirmasi melalui WhatsApp 0812-1201-2031 sebelum kunjungan.</div></SimplePage>}
function Information({openInfo}){return <SimplePage eyebrow="Pusat informasi Dukcapil" title="Pengumuman, panduan, dan dokumen" text="Konten tersedia langsung di portal ini tanpa mengalihkan Anda ke website lama."><div className="cards info-cards">{informationItems.map(item=><article key={item.id}><span>{item.tag}</span><h2>{item.title}</h2><p>{item.summary}</p><button onClick={()=>openInfo(item.id)}>Baca informasi <ArrowRight/></button></article>)}</div></SimplePage>}
function InformationDetail({item,back}){return <section className="shell page info-detail"><button className="back" onClick={back}><ArrowLeft/> Kembali ke pusat informasi</button><article><span>{item.tag}</span><h1>{item.title}</h1><small><CalendarDays/> {item.date}</small>{item.body.map(p=><p key={p}>{p}</p>)}{item.id==="forms"&&<div className="form-groups">{["Biodata penduduk dan Kartu Keluarga","Perpindahan penduduk","Kelahiran dan kematian","Perkawinan dan perceraian","Perubahan elemen data","Warga negara asing"].map((x,i)=><div key={x}><b>F-{String(i+1).padStart(2,"0")}</b><span>{x}</span></div>)}</div>}{item.links.length>0&&<div className="detail-links">{item.links.map(([label,url])=><External key={label} href={url}>{label}<ArrowRight/></External>)}</div>}<button className="print primary" onClick={()=>window.print()}><Printer/> Cetak informasi</button></article></section>}
function Help({openFaq,setOpenFaq}){const channels=[[Phone,"WhatsApp Dukcapil","0812-1201-2031","https://wa.me/6281212012031"],[MessageCircle,"Pengaduan CRM Jakarta","Sampaikan keluhan melalui kanal resmi","https://pengaduanwarga.jakarta.go.id/"],[Mail,"Permohonan informasi","Ajukan melalui portal PPID DKI","https://ppid.jakarta.go.id/"]];return <SimplePage eyebrow="Bantuan warga" title="Ada yang bisa kami bantu?" text="Temukan jawaban cepat atau gunakan kanal resmi yang sesuai. Jangan kirim foto dokumen kependudukan sebelum petugas resmi memintanya."><div className="contact-cards">{channels.map(([Icon,t,d,url])=><External key={t} href={url}><Icon/><b>{t}</b><small>{d}</small></External>)}</div><div className="faq"><p className="eyebrow">Pertanyaan umum</p><h2 className="section-title">Jawaban yang sering dicari</h2>{faq.map(([q,a],i)=><div key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}>{q}<ChevronDown className={openFaq===i?"rotate":""}/></button>{openFaq===i&&<p>{a}</p>}</div>)}</div></SimplePage>}
function Ppid(){const items=[[ShieldCheck,"Permohonan informasi","Ajukan permohonan dan keberatan informasi publik.","https://ppid.jakarta.go.id/permohonan-informasi"],[BookOpen,"Daftar informasi","Telusuri informasi publik perangkat daerah.","https://ppid.jakarta.go.id/daftar-informasi-publik"],[FileText,"Cek status","Pantau status permohonan informasi publik.","https://ppid.jakarta.go.id/"],[Users,"Portal PPID DKI","Akses statistik dan layanan informasi tingkat provinsi.","https://ppid.jakarta.go.id/"]];return <SimplePage eyebrow="Pejabat Pengelola Informasi dan Dokumentasi" title="Informasi publik yang mudah ditemukan" text="Gunakan jalur PPID untuk permohonan informasi, keberatan, dan penelusuran dokumen publik."><div className="cards">{items.map(([Icon,t,d,url])=><article key={t}><i><Icon/></i><h2>{t}</h2><p>{d}</p><External href={url}>Lihat selengkapnya <ArrowRight/></External></article>)}</div></SimplePage>}
function SimplePage({eyebrow,title,text,children}){return <section className="shell page"><p className="eyebrow">{eyebrow}</p><h1 className="page-title">{title}</h1>{text&&<p className="lead">{text}</p>}{children}</section>}
function Footer({find,go,openInfo}){return <footer><div className="shell footer-grid"><div className="footer-about"><div><Emblem/><span><small>Pemerintah Provinsi DKI Jakarta</small><b>Dinas Kependudukan dan Pencatatan Sipil</b></span></div><p>Portal informasi layanan administrasi kependudukan dan pencatatan sipil bagi warga DKI Jakarta.</p><p>Jl. Letjen S. Parman No. 7, Tomang, Jakarta Barat · WhatsApp 0812-1201-2031</p></div><div><b>Layanan</b><button onClick={()=>find()}>Cari layanan</button><button onClick={()=>go("locations")}>Lokasi & kanal</button><button onClick={()=>go("help")}>Bantuan warga</button></div><div><b>Informasi</b><button onClick={()=>go("information")}>Pengumuman</button><button onClick={()=>openInfo("standards")}>Standar pelayanan</button><button onClick={()=>go("ppid")}>PPID</button></div></div><div className="copyright"><div className="shell">© 2026 Dinas Kependudukan dan Pencatatan Sipil Provinsi DKI Jakarta <span><button onClick={()=>go("home")}>Beranda</button> · <button onClick={()=>go("help")}>Bantuan</button> · <External href="https://ppid.jakarta.go.id/">Kebijakan informasi</External></span></div></div></footer>}
